### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by ErwannLeRoux** [Grafikart/CustomElement-DropFiles#2]
Firefox issue - image duplication when adding new image. 

add image A = A
add image B = AAB
add image C = AABABC

Same issue when removing. Element view seems to don't refresh.

![image](https://user-images.githubusercontent.com/25199729/70709118-70daed00-1cdc-11ea-9de3-1723071002ee.png)

**Comment by Grafikart** [comment]
Merci pour le signalement je ne l'avais pas vu passer celui là ;)

**Comment by ErwannLeRoux** [comment]
Avec plaisir, merci pour la qualité de ton contenu :)
