### ISSUE TITLE
Upload one file

### ISSUE THREAD

**Issue by oza75** [Grafikart/CustomElement-DropFiles#4]
First of all, I found this library very interesting. Just a way it use custom element and don't require ajax request is very helpul.
 
But if,  for example I want to **upload only one image**  but want to have a nice view for the user (remove image, have the image thumbnail etc... )  

`
<input
          type="file"
          name="image"
          label="Drop your image there."
          is="drop-files"
        />`

this library do not support this and keep adding files ( I just want one file, if there is already a file and user want to add another the first one must be replaced ) 

I think we can do this by checking if the `multiple` attribute is false

**Comment by Grafikart** [comment]
This is fixed (upgrade to the 1.0.8 to see the change)
