### ISSUE TITLE
Show already uploaded files

### ISSUE THREAD

**Issue by oversoul** [Grafikart/CustomElement-DropFiles#5]
Hello,

I'm trying to show previously uploaded files.

i can't see a way to do it.

**Comment by hanako-eo** [comment]
are you trying to do that with your own css?

**Comment by oversoul** [comment]
no not really, i'm looking for a way so i can provide the element with previously uploaded files (links) and it can show them, similarly to an input value.

**Comment by Grafikart** [comment]
How would you manage this with the native input element ?

**Comment by oversoul** [comment]
I'm talking about the (text, select, ...) inputs, not the file input obviously.

**Comment by hanako-eo** [comment]
files from external site?

**Comment by oversoul** [comment]
no, just the previously uploaded files.
